export interface PublicGift {
  id: string;
  slug: string;
  name: string;
  description: string;
  category: string;
  image_url: string | null;
  external_url: string | null;
  external_note: string | null;
  preferences: Record<string, unknown> | null;
  display_order: number;
  is_reserved: boolean;
  is_active?: boolean;
}

// 69 presentes oficiais organizados pelas 8 categorias do CEO
export const REAL_GIFTS: PublicGift[] = [
  // --- 1. ITENS MAIS PEDIDOS ---
  {
    id: "g-mp-01",
    slug: "air-fryer",
    name: "Air fryer",
    description: "Fritadeira elétrica sem óleo para refeições práticas e saudáveis no nosso dia a dia.",
    category: "Itens mais pedidos",
    image_url: "https://images.unsplash.com/photo-1585515320310-259814833e62?auto=format&fit=crop&w=800&q=80",
    external_url: null,
    external_note: "110V ou 220V (qualquer voltagem nos atende).",
    preferences: { voltagem: "110V ou 220V" },
    display_order: 1,
    is_reserved: false,
    is_active: true,
  },
  {
    id: "g-mp-02",
    slug: "liquidificador",
    name: "Liquidificador",
    description: "Liquidificador potente com jarra resistente para sucos, vitaminas e receitas.",
    category: "Itens mais pedidos",
    image_url: "https://images.unsplash.com/photo-1570222094114-d054a817e56b?auto=format&fit=crop&w=800&q=80",
    external_url: null,
    external_note: null,
    preferences: { voltagem: "110V" },
    display_order: 2,
    is_reserved: false,
    is_active: true,
  },
  {
    id: "g-mp-03",
    slug: "mixer",
    name: "Mixer",
    description: "Mixer manual para preparar molhos, sopas e cremes diretamente na panela.",
    category: "Itens mais pedidos",
    image_url: "https://images.unsplash.com/photo-1594385208974-2e75f8d7bb48?auto=format&fit=crop&w=800&q=80",
    external_url: null,
    external_note: null,
    preferences: null,
    display_order: 3,
    is_reserved: false,
    is_active: true,
  },
  {
    id: "g-mp-04",
    slug: "sanduicheira",
    name: "Sanduicheira",
    description: "Sanduicheira e grill antiaderente para lanches rápidos e tostados.",
    category: "Itens mais pedidos",
    image_url: "https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?auto=format&fit=crop&w=800&q=80",
    external_url: null,
    external_note: null,
    preferences: null,
    display_order: 4,
    is_reserved: false,
    is_active: true,
  },
  {
    id: "g-mp-05",
    slug: "cafeteira",
    name: "Cafeteira",
    description: "Cafeteira para acompanhar nossos cafés da manhã e momentos especiais.",
    category: "Itens mais pedidos",
    image_url: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=80",
    external_url: null,
    external_note: null,
    preferences: null,
    display_order: 5,
    is_reserved: false,
    is_active: true,
  },
  {
    id: "g-mp-06",
    slug: "chaleira-eletrica",
    name: "Chaleira elétrica",
    description: "Chaleira elétrica rápida para aquecer água de cafés, chás e receitas.",
    category: "Itens mais pedidos",
    image_url: "https://images.unsplash.com/photo-1570784332176-fdd73da66f03?auto=format&fit=crop&w=800&q=80",
    external_url: null,
    external_note: null,
    preferences: null,
    display_order: 6,
    is_reserved: false,
    is_active: true,
  },
  {
    id: "g-mp-07",
    slug: "processador-de-alimentos",
    name: "Processador de alimentos",
    description: "Processador compacto para picar, ralar e triturar ingredientes com agilidade.",
    category: "Itens mais pedidos",
    image_url: null,
    external_url: null,
    external_note: null,
    preferences: null,
    display_order: 7,
    is_reserved: false,
    is_active: true,
  },
  {
    id: "g-mp-08",
    slug: "jogo-de-potes-de-vidro",
    name: "Jogo de potes de vidro",
    description: "Conjunto de potes de vidro com vedação hermética para armazenar alimentos.",
    category: "Itens mais pedidos",
    image_url: "https://images.unsplash.com/photo-1584990347449-397a66e6c1e5?auto=format&fit=crop&w=800&q=80",
    external_url: null,
    external_note: null,
    preferences: null,
    display_order: 8,
    is_reserved: false,
    is_active: true,
  },

  // --- 2. COZINHA ---
  {
    id: "g-coz-01",
    slug: "jogo-de-panelas",
    name: "Jogo de panelas",
    description: "Conjunto completo de panelas antiaderentes para a nossa nova cozinha.",
    category: "Cozinha",
    image_url: "https://images.unsplash.com/photo-1584990347449-397a66e6c1e5?auto=format&fit=crop&w=800&q=80",
    external_url: null,
    external_note: "Preferência por tons neutros (terracota, grafite ou bege).",
    preferences: null,
    display_order: 9,
    is_reserved: false,
    is_active: true,
  },
  {
    id: "g-coz-02",
    slug: "frigideiras",
    name: "Frigideiras",
    description: "Frigideiras antiaderentes em tamanhos variados para o dia a dia.",
    category: "Cozinha",
    image_url: null,
    external_url: null,
    external_note: null,
    preferences: null,
    display_order: 10,
    is_reserved: false,
    is_active: true,
  },
  {
    id: "g-coz-03",
    slug: "assadeiras",
    name: "Assadeiras",
    description: "Conjunto de assadeiras retangulares e ovais para fornos e doces.",
    category: "Cozinha",
    image_url: null,
    external_url: null,
    external_note: null,
    preferences: null,
    display_order: 11,
    is_reserved: false,
    is_active: true,
  },
  {
    id: "g-coz-04",
    slug: "forma-para-bolo",
    name: "Forma para bolo",
    description: "Forma redonda com furo central e formas tradicionais para bolos caseiros.",
    category: "Cozinha",
    image_url: null,
    external_url: null,
    external_note: null,
    preferences: null,
    display_order: 12,
    is_reserved: false,
    is_active: true,
  },
  {
    id: "g-coz-05",
    slug: "escorredor-de-macarrao",
    name: "Escorredor de macarrão",
    description: "Escorredor resistente em aço inox com base estável.",
    category: "Cozinha",
    image_url: null,
    external_url: null,
    external_note: null,
    preferences: null,
    display_order: 13,
    is_reserved: false,
    is_active: true,
  },
  {
    id: "g-coz-06",
    slug: "peneiras",
    name: "Peneiras",
    description: "Conjunto de peneiras finas em aço inox em tamanhos diversos.",
    category: "Cozinha",
    image_url: null,
    external_url: null,
    external_note: null,
    preferences: null,
    display_order: 14,
    is_reserved: false,
    is_active: true,
  },
  {
    id: "g-coz-07",
    slug: "tabuas-de-corte",
    name: "Tábuas de corte",
    description: "Tábuas de corte em madeira natural ou bambu para preparo de alimentos.",
    category: "Cozinha",
    image_url: null,
    external_url: null,
    external_note: null,
    preferences: null,
    display_order: 15,
    is_reserved: false,
    is_active: true,
  },
  {
    id: "g-coz-08",
    slug: "facas-chef-pao-legumes",
    name: "Facas (chef, pão e legumes)",
    description: "Conjunto essencial de facas de alta precisão em aço forjado.",
    category: "Cozinha",
    image_url: "https://images.unsplash.com/photo-1593618998160-e34014e67546?auto=format&fit=crop&w=800&q=80",
    external_url: null,
    external_note: null,
    preferences: null,
    display_order: 16,
    is_reserved: false,
    is_active: true,
  },
  {
    id: "g-coz-09",
    slug: "conchas-escumadeiras-espatulas",
    name: "Conchas, escumadeiras e espátulas",
    description: "Kit de utensílios para servir e cozinhar com cabos confortáveis.",
    category: "Cozinha",
    image_url: null,
    external_url: null,
    external_note: null,
    preferences: null,
    display_order: 17,
    is_reserved: false,
    is_active: true,
  },
  {
    id: "g-coz-10",
    slug: "abridor-de-latas-e-garrafas",
    name: "Abridor de latas e garrafas",
    description: "Abridores anatômicos e resistentes em inox.",
    category: "Cozinha",
    image_url: null,
    external_url: null,
    external_note: null,
    preferences: null,
    display_order: 18,
    is_reserved: false,
    is_active: true,
  },
  {
    id: "g-coz-11",
    slug: "ralador",
    name: "Ralador",
    description: "Ralador multifuncional de 4 faces em aço inox.",
    category: "Cozinha",
    image_url: null,
    external_url: null,
    external_note: null,
    preferences: null,
    display_order: 19,
    is_reserved: false,
    is_active: true,
  },
  {
    id: "g-coz-12",
    slug: "descascador-de-legumes",
    name: "Descascador de legumes",
    description: "Descascador em formato Y com lâmina afiada.",
    category: "Cozinha",
    image_url: null,
    external_url: null,
    external_note: null,
    preferences: null,
    display_order: 20,
    is_reserved: false,
    is_active: true,
  },
  {
    id: "g-coz-13",
    slug: "medidores-xicaras-e-colheres",
    name: "Medidores (xícaras e colheres)",
    description: "Conjunto de colheres e xícaras medidoras para receitas precisas.",
    category: "Cozinha",
    image_url: null,
    external_url: null,
    external_note: null,
    preferences: null,
    display_order: 21,
    is_reserved: false,
    is_active: true,
  },
  {
    id: "g-coz-14",
    slug: "tigelas-bowls",
    name: "Tigelas (bowls)",
    description: "Kit de tigelas em cerâmica ou inox para misturas e servir.",
    category: "Cozinha",
    image_url: null,
    external_url: null,
    external_note: null,
    preferences: null,
    display_order: 22,
    is_reserved: false,
    is_active: true,
  },
  {
    id: "g-coz-15",
    slug: "potes-hermeticos",
    name: "Potes herméticos",
    description: "Potes herméticos para organização de mantimentos secos.",
    category: "Cozinha",
    image_url: null,
    external_url: null,
    external_note: null,
    preferences: null,
    display_order: 23,
    is_reserved: false,
    is_active: true,
  },
  {
    id: "g-coz-16",
    slug: "jarra-para-agua-ou-suco",
    name: "Jarra para água ou suco",
    description: "Jarra de vidro elegante com bico dosador.",
    category: "Cozinha",
    image_url: null,
    external_url: null,
    external_note: null,
    preferences: null,
    display_order: 24,
    is_reserved: false,
    is_active: true,
  },

  // --- 3. MESA E SERVIR ---
  {
    id: "g-mes-01",
    slug: "aparelho-de-jantar",
    name: "Aparelho de jantar",
    description: "Conjunto completo de pratos e xícaras para nossas refeições em família.",
    category: "Mesa e Servir",
    image_url: null,
    external_url: null,
    external_note: null,
    preferences: null,
    display_order: 25,
    is_reserved: false,
    is_active: true,
  },
  {
    id: "g-mes-02",
    slug: "pratos-rasos-fundos-sobremesa",
    name: "Pratos rasos, fundos e de sobremesa",
    description: "Pratos em cerâmica artesanal em tons neutros.",
    category: "Mesa e Servir",
    image_url: null,
    external_url: null,
    external_note: null,
    preferences: null,
    display_order: 26,
    is_reserved: false,
    is_active: true,
  },
  {
    id: "g-mes-03",
    slug: "copos",
    name: "Copos",
    description: "Conjunto de copos de vidro para o dia a dia.",
    category: "Mesa e Servir",
    image_url: null,
    external_url: null,
    external_note: null,
    preferences: null,
    display_order: 27,
    is_reserved: false,
    is_active: true,
  },
  {
    id: "g-mes-04",
    slug: "tacas",
    name: "Taças",
    description: "Conjunto de taças de cristal ecológico para celebrações.",
    category: "Mesa e Servir",
    image_url: null,
    external_url: null,
    external_note: null,
    preferences: null,
    display_order: 28,
    is_reserved: false,
    is_active: true,
  },
  {
    id: "g-mes-05",
    slug: "xicaras-e-pires",
    name: "Xícaras e pires",
    description: "Conjunto de xícaras para café e chá da tarde.",
    category: "Mesa e Servir",
    image_url: null,
    external_url: null,
    external_note: null,
    preferences: null,
    display_order: 29,
    is_reserved: false,
    is_active: true,
  },
  {
    id: "g-mes-06",
    slug: "talheres",
    name: "Talheres",
    description: "Faqueiro completo em aço inox com acabamento polido.",
    category: "Mesa e Servir",
    image_url: null,
    external_url: null,
    external_note: null,
    preferences: null,
    display_order: 30,
    is_reserved: false,
    is_active: true,
  },
  {
    id: "g-mes-07",
    slug: "travessas",
    name: "Travessas",
    description: "Travessas refratárias para servir à mesa.",
    category: "Mesa e Servir",
    image_url: null,
    external_url: null,
    external_note: null,
    preferences: null,
    display_order: 31,
    is_reserved: false,
    is_active: true,
  },
  {
    id: "g-mes-08",
    slug: "petisqueiras",
    name: "Petisqueiras",
    description: "Petisqueiras com divisórias em madeira ou cerâmica.",
    category: "Mesa e Servir",
    image_url: null,
    external_url: null,
    external_note: null,
    preferences: null,
    display_order: 32,
    is_reserved: false,
    is_active: true,
  },
  {
    id: "g-mes-09",
    slug: "jogo-americano",
    name: "Jogo americano",
    description: "Conjunto de jogos americanos em linho ou fibra natural.",
    category: "Mesa e Servir",
    image_url: null,
    external_url: null,
    external_note: null,
    preferences: null,
    display_order: 33,
    is_reserved: false,
    is_active: true,
  },
  {
    id: "g-mes-10",
    slug: "toalha-de-mesa",
    name: "Toalha de mesa",
    description: "Toalha de mesa em tecido natural com toque suave.",
    category: "Mesa e Servir",
    image_url: null,
    external_url: null,
    external_note: null,
    preferences: null,
    display_order: 34,
    is_reserved: false,
    is_active: true,
  },

  // --- 4. CAFÉ E CAFÉ DA MANHÃ ---
  {
    id: "g-caf-01",
    slug: "garrafa-termica",
    name: "Garrafa térmica",
    description: "Garrafa térmica com excelente retenção de calor e design retrô.",
    category: "Café e Café da Manhã",
    image_url: null,
    external_url: null,
    external_note: null,
    preferences: null,
    display_order: 35,
    is_reserved: false,
    is_active: true,
  },
  {
    id: "g-caf-02",
    slug: "acucareiro",
    name: "Açucareiro",
    description: "Açucareiro em cerâmica com colherzinha dosadora.",
    category: "Café e Café da Manhã",
    image_url: null,
    external_url: null,
    external_note: null,
    preferences: null,
    display_order: 36,
    is_reserved: false,
    is_active: true,
  },
  {
    id: "g-caf-03",
    slug: "bule",
    name: "Bule",
    description: "Bule para servir café e chá à mesa.",
    category: "Café e Café da Manhã",
    image_url: null,
    external_url: null,
    external_note: null,
    preferences: null,
    display_order: 37,
    is_reserved: false,
    is_active: true,
  },
  {
    id: "g-caf-04",
    slug: "porta-filtro-de-cafe",
    name: "Porta-filtro de café",
    description: "Suporte coador em cerâmica ou acrílico para café passado na hora.",
    category: "Café e Café da Manhã",
    image_url: null,
    external_url: null,
    external_note: null,
    preferences: null,
    display_order: 38,
    is_reserved: false,
    is_active: true,
  },
  {
    id: "g-caf-05",
    slug: "bandeja-para-servir",
    name: "Bandeja para servir",
    description: "Bandeja em madeira clara ou bambu com alças.",
    category: "Café e Café da Manhã",
    image_url: null,
    external_url: null,
    external_note: null,
    preferences: null,
    display_order: 39,
    is_reserved: false,
    is_active: true,
  },

  // --- 5. LIMPEZA ---
  {
    id: "g-lim-01",
    slug: "balde",
    name: "Balde",
    description: "Balde resistente com alça reforçada e bico dosador.",
    category: "Limpeza",
    image_url: null,
    external_url: null,
    external_note: null,
    preferences: null,
    display_order: 40,
    is_reserved: false,
    is_active: true,
  },
  {
    id: "g-lim-02",
    slug: "vassoura",
    name: "Vassoura",
    description: "Vassoura de cerdas macias com cabo ergonômico.",
    category: "Limpeza",
    image_url: null,
    external_url: null,
    external_note: null,
    preferences: null,
    display_order: 41,
    is_reserved: false,
    is_active: true,
  },
  {
    id: "g-lim-03",
    slug: "rodo",
    name: "Rodo",
    description: "Rodo com borracha dupla para puxar água com facilidade.",
    category: "Limpeza",
    image_url: null,
    external_url: null,
    external_note: null,
    preferences: null,
    display_order: 42,
    is_reserved: false,
    is_active: true,
  },
  {
    id: "g-lim-04",
    slug: "pa-de-lixo",
    name: "Pá de lixo",
    description: "Pá com borda emborrachada para recolhimento ágil.",
    category: "Limpeza",
    image_url: null,
    external_url: null,
    external_note: null,
    preferences: null,
    display_order: 43,
    is_reserved: false,
    is_active: true,
  },
  {
    id: "g-lim-05",
    slug: "esponjas",
    name: "Esponjas",
    description: "Kit de esponjas de limpeza multiuso e antiaderentes.",
    category: "Limpeza",
    image_url: null,
    external_url: null,
    external_note: null,
    preferences: null,
    display_order: 44,
    is_reserved: false,
    is_active: true,
  },
  {
    id: "g-lim-06",
    slug: "panos-de-prato",
    name: "Panos de prato",
    description: "Kit de panos de prato 100% algodão de alta absorção.",
    category: "Limpeza",
    image_url: null,
    external_url: null,
    external_note: null,
    preferences: null,
    display_order: 45,
    is_reserved: false,
    is_active: true,
  },
  {
    id: "g-lim-07",
    slug: "panos-de-limpeza",
    name: "Panos de limpeza",
    description: "Kit de panos de microfibra para limpeza de superfícies.",
    category: "Limpeza",
    image_url: null,
    external_url: null,
    external_note: null,
    preferences: null,
    display_order: 46,
    is_reserved: false,
    is_active: true,
  },
  {
    id: "g-lim-08",
    slug: "cesto-de-lixo",
    name: "Cesto de lixo",
    description: "Lixeira com pedal em aço inox ou acabamento neutro.",
    category: "Limpeza",
    image_url: null,
    external_url: null,
    external_note: null,
    preferences: null,
    display_order: 47,
    is_reserved: false,
    is_active: true,
  },
  {
    id: "g-lim-09",
    slug: "varal-de-chao",
    name: "Varal de chão",
    description: "Varal dobrável com abas para secagem de roupas.",
    category: "Limpeza",
    image_url: null,
    external_url: null,
    external_note: null,
    preferences: null,
    display_order: 48,
    is_reserved: false,
    is_active: true,
  },
  {
    id: "g-lim-10",
    slug: "prendedores-de-roupa",
    name: "Prendedores de roupa",
    description: "Conjunto de prendedores em madeira ou silicone reforçado.",
    category: "Limpeza",
    image_url: null,
    external_url: null,
    external_note: null,
    preferences: null,
    display_order: 49,
    is_reserved: false,
    is_active: true,
  },

  // --- 6. QUARTO E BANHEIRO ---
  {
    id: "g-qb-01",
    slug: "jogo-de-lencois",
    name: "Jogo de lençóis",
    description: "Jogo de cama em algodão percal para cama casal/queen.",
    category: "Quarto e Banheiro",
    image_url: null,
    external_url: null,
    external_note: "Cama padrão Casal / Queen.",
    preferences: { tamanho: "Queen / Casal" },
    display_order: 50,
    is_reserved: false,
    is_active: true,
  },
  {
    id: "g-qb-02",
    slug: "travesseiros",
    name: "Travesseiros",
    description: "Travesseiros confortáveis de suporte médio.",
    category: "Quarto e Banheiro",
    image_url: null,
    external_url: null,
    external_note: null,
    preferences: null,
    display_order: 51,
    is_reserved: false,
    is_active: true,
  },
  {
    id: "g-qb-03",
    slug: "protetor-de-colchao",
    name: "Protetor de colchão",
    description: "Capa protetora impermeável e respirável para colchão.",
    category: "Quarto e Banheiro",
    image_url: null,
    external_url: null,
    external_note: null,
    preferences: null,
    display_order: 52,
    is_reserved: false,
    is_active: true,
  },
  {
    id: "g-qb-04",
    slug: "toalhas-de-banho",
    name: "Toalhas de banho",
    description: "Toalhas de banho macias e felpudas 100% algodão.",
    category: "Quarto e Banheiro",
    image_url: null,
    external_url: null,
    external_note: null,
    preferences: null,
    display_order: 53,
    is_reserved: false,
    is_active: true,
  },
  {
    id: "g-qb-05",
    slug: "toalhas-de-rosto",
    name: "Toalhas de rosto",
    description: "Conjunto de toalhas de rosto coordenadas.",
    category: "Quarto e Banheiro",
    image_url: null,
    external_url: null,
    external_note: null,
    preferences: null,
    display_order: 54,
    is_reserved: false,
    is_active: true,
  },
  {
    id: "g-qb-06",
    slug: "tapete-para-banheiro",
    name: "Tapete para banheiro",
    description: "Tapete antiderrapante em algodão de secagem rápida.",
    category: "Quarto e Banheiro",
    image_url: null,
    external_url: null,
    external_note: null,
    preferences: null,
    display_order: 55,
    is_reserved: false,
    is_active: true,
  },
  {
    id: "g-qb-07",
    slug: "cesto-para-roupas",
    name: "Cesto para roupas",
    description: "Cesto organizador de roupas em tecido estruturado ou bambu.",
    category: "Quarto e Banheiro",
    image_url: null,
    external_url: null,
    external_note: null,
    preferences: null,
    display_order: 56,
    is_reserved: false,
    is_active: true,
  },

  // --- 7. ORGANIZAÇÃO ---
  {
    id: "g-org-01",
    slug: "cabides",
    name: "Cabides",
    description: "Conjunto de cabides aveludados finos para otimizar espaço.",
    category: "Organização",
    image_url: null,
    external_url: null,
    external_note: null,
    preferences: null,
    display_order: 57,
    is_reserved: false,
    is_active: true,
  },
  {
    id: "g-org-02",
    slug: "organizadores-de-gaveta",
    name: "Organizadores de gaveta",
    description: "Divisórias modulares para gavetas de roupas e armários.",
    category: "Organização",
    image_url: null,
    external_url: null,
    external_note: null,
    preferences: null,
    display_order: 58,
    is_reserved: false,
    is_active: true,
  },
  {
    id: "g-org-03",
    slug: "caixas-organizadoras",
    name: "Caixas organizadoras",
    description: "Caixas organizadoras com tampa para armários e prateleiras.",
    category: "Organização",
    image_url: null,
    external_url: null,
    external_note: null,
    preferences: null,
    display_order: 59,
    is_reserved: false,
    is_active: true,
  },
  {
    id: "g-org-04",
    slug: "porta-sabonete",
    name: "Porta-sabonete",
    description: "Saboneteira em cerâmica neutra ou bambu.",
    category: "Organização",
    image_url: null,
    external_url: null,
    external_note: null,
    preferences: null,
    display_order: 60,
    is_reserved: false,
    is_active: true,
  },
  {
    id: "g-org-05",
    slug: "porta-escovas-de-dente",
    name: "Porta-escovas de dente",
    description: "Suporte higiênico para escovas de dente combinando com a bancada.",
    category: "Organização",
    image_url: null,
    external_url: null,
    external_note: null,
    preferences: null,
    display_order: 61,
    is_reserved: false,
    is_active: true,
  },
  {
    id: "g-org-06",
    slug: "ganchos-adesivos",
    name: "Ganchos adesivos",
    description: "Ganchos multiuso de fixação sem furos.",
    category: "Organização",
    image_url: null,
    external_url: null,
    external_note: null,
    preferences: null,
    display_order: 62,
    is_reserved: false,
    is_active: true,
  },

  // --- 8. ITENS CORINGA ---
  {
    id: "g-cor-01",
    slug: "vale-presente",
    name: "Vale-presente",
    description: "Contribuição flexível para nos ajudar a completar o que faltar no novo lar.",
    category: "Itens Coringa",
    image_url: null,
    external_url: null,
    external_note: "Fique à vontade com qualquer valor ou loja de sua preferência.",
    preferences: null,
    display_order: 63,
    is_reserved: false,
    is_active: true,
  },
  {
    id: "g-cor-02",
    slug: "kit-de-temperos",
    name: "Kit de temperos",
    description: "Seleção de especiarias e ervas para temperar com carinho nossas refeições.",
    category: "Itens Coringa",
    image_url: "https://images.unsplash.com/photo-1532336414038-cf19250c5757?auto=format&fit=crop&w=800&q=80",
    external_url: null,
    external_note: null,
    preferences: null,
    display_order: 64,
    is_reserved: false,
    is_active: true,
  },
  {
    id: "g-cor-03",
    slug: "kit-de-utensilios-de-silicone",
    name: "Kit de utensílios de silicone",
    description: "Espátulas e colheres de silicone culinário que não riscam panelas.",
    category: "Itens Coringa",
    image_url: null,
    external_url: null,
    external_note: null,
    preferences: null,
    display_order: 65,
    is_reserved: false,
    is_active: true,
  },
  {
    id: "g-cor-04",
    slug: "kit-de-potes",
    name: "Kit de potes",
    description: "Conjunto de potes utilitários para porções e lanches.",
    category: "Itens Coringa",
    image_url: null,
    external_url: null,
    external_note: null,
    preferences: null,
    display_order: 66,
    is_reserved: false,
    is_active: true,
  },
  {
    id: "g-cor-05",
    slug: "jogo-de-panos-de-prato",
    name: "Jogo de panos de prato",
    description: "Panos de prato decorativos e funcionais para a cozinha.",
    category: "Itens Coringa",
    image_url: null,
    external_url: null,
    external_note: null,
    preferences: null,
    display_order: 67,
    is_reserved: false,
    is_active: true,
  },
  {
    id: "g-cor-06",
    slug: "velas-aromaticas",
    name: "Velas aromáticas",
    description: "Velas perfumadas com essências suaves para aconchego do lar.",
    category: "Itens Coringa",
    image_url: null,
    external_url: null,
    external_note: "Aromas suaves (baunilha, lavanda ou alecrim).",
    preferences: null,
    display_order: 68,
    is_reserved: false,
    is_active: true,
  },
  {
    id: "g-cor-07",
    slug: "difusor-de-ambiente",
    name: "Difusor de ambiente",
    description: "Difusor de varetas com aroma acolhedor para a casa.",
    category: "Itens Coringa",
    image_url: null,
    external_url: null,
    external_note: null,
    preferences: null,
    display_order: 69,
    is_reserved: false,
    is_active: true,
  },
];

export const DEMO_GIFTS = REAL_GIFTS;
